sudo: required
language: generic

services:
  - docker

script:
  - docker build -t nikitaproks/safemoon -f ./backend/Dockerfile ./backend
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push build -t nikitaproks/safemoon

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "safemoon"
  env: "safemoon-env"
  bucket_name: "elasticbeanstalk-eu-central-1-195149449576"
  bucket_path: "safemoon"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
